# Generated by Django 4.2.20 on 2025-03-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddle_app', '0003_rename_category_riddle_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='difficulty',
            field=models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=None, max_length=1),
        ),
    ]
