# Generated by Django 4.2.20 on 2025-03-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddle_app', '0004_alter_riddle_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='likes',
        ),
    ]
